# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llhCNM7TvgcxyvzGvInFb3nf5P1uMRtt
"""

def process_payment(customer_name, amount):

    print(f"Mijoz ismi: {customer_name}")
    print(f"To'lov miqdori: ${amount:.2f}")

    if amount > 0:
        print("To'lov muvaffaqiyatli amalga oshirildi!")
    else:
        print("To'lov miqdori noto'g'ri kiritilgan.")


def main():

    customer_name = input("Mijoz ismini kiriting: ")
    try:
        amount = float(input("To'lov miqdorini kiriting ($): "))
        process_payment(customer_name, amount)
    except ValueError:
        print("Iltimos, to'g'ri raqamli qiymat kiriting!")


if __name__ == "__main__":
    main()